[package]
name = "oikurs"
version = "0.3.1"
authors = ["bouzuya <m@bouzuya.net>"]
edition = "2021"

[dependencies]
anyhow = "1.0.58"
regex = "1.6.0"
reqwest = "0.11.11"
scraper = "0.13.0"
tokio = { version = "1.19.2", features = ["full"] }
url = "2.2.2"
